[tool.poetry]
authors = ["Darkflame72 <leon@bowie-co.nz>"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Topic :: Games/Entertainment",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Utilities",
]
description = "An async wrapper for minecraft server stats"
documentation = "https://mcsrvstats.readthedocs.io"
license = "MIT"
name = "mcsrvstats"
readme = "README.md"
repository = "https://github.com/Obsidion-dev/mcsrvstats"
version = "0.1.1"

[tool.poetry.dependencies]
aiohttp = "^3.6.2"
bs4 = "^0.0.1"
importlib_metadata = {version = "^2.0.0", python = "<3.8"}
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
codecov = "^2.1.9"
coverage = {extras = ["toml"], version = "^5.3"}
darglint = "^1.5.4"
flake8 = "^3.8.3"
flake8-annotations = "^2.4.0"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.1"
flake8-bugbear = "^20.1.4"
flake8-docstrings = "^1.5.0"
flake8-import-order = "^0.18.1"
mypy = "^0.782"
pytest = "^5.0"
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"
pytype = {version = "^2020.9.16", python = "3.7"}
safety = "^1.9.0"
sphinx = "^3.2.1"
sphinx-autodoc-typehints = "^1.11.0"
typeguard = "^2.9.1"

[tool.black]
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
include = '\.pyi?$'
line-length = 88
target-version = ['py36', 'py37', 'py38']
[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["mcsrvstats"]

[tool.coverage.report]
show_missing = true
#fail_under = 100
[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

# pyproject.toml
