"""Models for mcsrvstats data objects."""
from .gommehd import *
from .manacube import *
from .universocraft import *
from .veltpvp import *
from .wyncraft_classes import *

__all__ = [
    "Manacube",
    "Parkour",
    "Aztec",
    "Oasis",
    "Islands",
    "Survival",
    "Factions",
    "Aether",
    "Atlas",
    "Creative",
    "Kitpvp",
    "WyncraftClasses",
    "Classes",
    "DestoryNexus",
    "SkyWars",
    "LuckyWars",
    "EggWars",
    "TeamSkyWars",
    "BedWars",
    "SpeedBuilders",
    "BuildBattle",
    "EscapeBeast",
    "PartyGames",
    "SkyPit",
    "UHC",
    "MurderMystery",
    "CaptureWool",
    "ArenaPVP",
    "HungerGames",
    "Universocraft",
    "TTT",
    "BedWarsGomme",
    "SkyWarsGomme",
    "SurvivalGames",
    "EnderGames",
    "QuickSurvivalGames",
    "Cores",
    "GunGame",
    "SpeedUHC",
    "MasterBuilders",
    "Cookies",
    "Hardcore",
    "GommeHD",
    "HCF",
    "Practice",
    "Soup",
    "Veltpvp",
]
